FROM vaporio/vapor-endpoint-base-x64:1.0
MAINTAINER Erick Daniszewski <erick@vapor.io>

# Wheel and setuptools need to be installed first in order to install the other python requirements.
RUN pip install --upgrade pip
RUN pip install wheel setuptools
RUN pip install -I \
    pycrypto

ADD . /emulator
WORKDIR /emulator

EXPOSE 623/udp

ENTRYPOINT ["python",  "-u", "ipmi_emulator.py"]
