# .chartreleaser.yaml is the configuration file for chart-releaser, a CI tool
# to update Helm Charts on application release. See the documentation at
# https://github.com/edaniszewski/chart-releaser

version: v1
chart:
  name: synse-server
  repo: github.com/vapor-ware/synse-charts
  path: synse-server
publish:
  pr:
    title_template: '[{{ .Chart.Name }}] bump app version from {{ .App.PreviousVersion}} to {{ .App.NewVersion }}'
commit:
  author:
    name: vio-bot
    email: marco+viogh@vapor.io
