version: "3"
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:local
    environment:
      - SYNSE_LOGGING=debug
      - SYNSE_PLUGIN_TCP=emulator:5001
    ports:
      - 5000:5000
    links:
      - emulator

  emulator:
    container_name: emulator
    image: vaporio/emulator-plugin
    ports:
      - 5001:5001
    command: ["--debug"]