#
# docker-compose.yml
#
# A simple deployment of Synse Server with an emulator plugin
# instance. Useful for learning, testing, and debugging.
#

version: '3.4'
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
    - '5000:5000'
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator-plugin-1:5001,emulator-plugin-2:5001
    links:
    - emulator-plugin-1
    - emulator-plugin-2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/test"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 5s

  emulator-plugin-1:
    container_name: emulator-plugin-1
    image: vaporio/emulator-plugin
    volumes:
      - ./cfg1.yaml:/etc/synse/plugin/config/config.yaml
    expose:
    - '5001'
    command: ['--debug']

  emulator-plugin-2:
    container_name: emulator-plugin-2
    image: vaporio/emulator-plugin
    volumes:
      - ./cfg2.yaml:/etc/synse/plugin/config/config.yaml
    expose:
      - '5001'
    command: ['--debug']
