version: 3
devices:
  - type: temperature
    metadata:
      model: emul8-temp
    instances:
      - info: Synse Temperature Sensor 1
        data:
          id: 1
      - info: Synse Temperature Sensor 2
        data:
          id: 2
      - info: Synse Temperature Sensor 3
        data:
          id: 3
      - info: Synse Temperature Sensor 4
        data:
          id: 4
      - info: Synse Temperature Sensor 5
        data:
          id: 5
  - type: pressure
    metadata:
      model: emul8-pressure
    instances:
      - info: Synse Pressure Sensor 1
        data:
          id: 1
      - info: Synse Pressure Sensor 2
        data:
          id: 2
  - type: led
    metadata:
      model: emul8-led
    instances:
      - info: Synse LED
        data:
          id: 1
      - info: Synse Backup LED
        data:
          id: 2
  - type: humidity
    metadata:
      model: emul8-humidity
    instances:
      - info: Synse Humidity Sensor
        data:
          id: 1
  - type: fan
    metadata:
      model: emul8-fan
    instances:
      - info: Synse Fan
        data:
          id: 1
  - type: airflow
    metadata:
      model: emul8-air
    instances:
      - info: Synse Airflow Sensor
        data:
          id: 1
