# Run tests for vapor-common components
#
#		\\//
#		 \/apor IO
#
# Author: Erick Daniszewski (erick@vapor.io)
#
# Copyright (C) 2015-16  Vapor IO
#
# This file is part of OpenDCRE.
#
#OpenDCRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# OpenDCRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenDCRE.  If not, see <http://www.gnu.org/licenses/>.

test:
	python -m unittest discover