#
# deploy-tcp.yml
#
# An example deployment of Synse Server and the Emulator Plugin
# configured to communicate over TCP.
#
version: "3"
services:

  # Synse Server
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:latest
    ports:
      - 5000:5000
    # TCP-based plugins can be registered with Synse Server via
    # environment variables, so we specify the plugin here.
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator-plugin:5001
      SYNSE_GRPC_TLS_CERT: /tmp/ssl/synseclient.crt
      SYNSE_GRPC_TLS_CA: /tmp/ssl/ca.crt
    volumes:
      - ./out/synseclient.crt:/tmp/ssl/synseclient.crt
      - ./out/Vapor_IO.crt:/tmp/ssl/ca.crt
    links:
      - emulator-plugin

  # Emulator Plugin
  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin:latest
    ports:
      - 5001:5001
    command: "--debug"
    volumes:
      # mount in the plugin config (see the environment section on how to
      # reference this non-default location)
      - ./config/tcp:/tmp/config/
      # mount in the device instance configuration (see the environment
      # section on how to reference this non-default location)
      - ./config/devices:/tmp/devices
      - ./out/pluginserver.crt:/tmp/ssl/pluginserver.crt
      - ./out/pluginserver.key:/tmp/ssl/pluginserver.key
      - ./out/Vapor_IO.crt:/tmp/ssl/Vapor_IO.crt
    environment:
      # sets the override location for the plugin configuration
      PLUGIN_CONFIG: /tmp/config
      # sets the override location for the device instance configuration
      PLUGIN_DEVICE_CONFIG: /tmp/devices
