#
# deploy-tcp.yml
#
# An example deployment of Synse Server and the Emulator Plugin
# configured to communicate over TCP.
#
version: "3"
services:

  # Synse Server
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:2.0.0
    ports:
      - 5000:5000
    # TCP-based plugins can be registered with Synse Server via
    # environment variables, so we specify the plugin here.
    environment:
      SYNSE_PLUGIN_TCP_EMULATOR: emulator-plugin:5001
    links:
      - emulator-plugin

  # Emulator Plugin
  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin
    ports:
      - 5001:5001
    volumes:
      # mount in the plugin config (see the environment section on how to
      # reference this non-default location)
      - ./config/tcp:/tmp/config/
      # mount in the device instance configuration (see the environment
      # section on how to reference this non-default location)
      - ./config/devices:/tmp/devices
    environment:
      # sets the override location for the plugin configuration
      PLUGIN_CONFIG: /tmp/config
      # sets the override location for the device instance configuration
      PLUGIN_DEVICE_PATH: /tmp/devices
