#
# deploy-tcp.yml
#
# An example deployment of Synse Server and the Emulator Plugin
# configured to communicate over TCP.
#
version: "3"
services:

  # Synse Server
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:latest
    ports:
      - 5000:5000
    # TCP-based plugins can be registered with Synse Server via
    # environment variables, so we specify the plugin here.
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator-plugin:5001
      # [TLS config]: specify the cert to use for gRPC TLS
      #SYNSE_GRPC_TLS_CERT: /tmp/ssl/emulator-plugin.crt
    # [TLS config]: volume is only needed for mounting in cert for TLS
    #volumes:
    #  - ./certs/emulator-plugin.crt:/tmp/ssl/emulator-plugin.crt
    links:
      - emulator-plugin

  # Emulator Plugin
  emulator-plugin:
    container_name: emulator-plugin
    image: vaporio/emulator-plugin:latest
    ports:
      - 5001:5001
    command: "--debug"
    volumes:
      # mount in the plugin config (see the environment section on how to
      # reference this non-default location)
      - ./config/tcp:/tmp/config/
      # mount in the device instance configuration (see the environment
      # section on how to reference this non-default location)
      - ./config/devices:/tmp/devices
      # [TLS config]: mount in the keys/certs needed for gRPC TLS
      #- ./certs/emulator-plugin.crt:/tmp/ssl/emulator-plugin.crt
      #- ./certs/emulator-plugin.key:/tmp/ssl/emulator-plugin.key
      #- ./certs/rootCA.crt:/tmp/ssl/rootCA.crt
    environment:
      # sets the override location for the plugin configuration
      PLUGIN_CONFIG: /tmp/config
      # sets the override location for the device instance configuration
      PLUGIN_DEVICE_CONFIG: /tmp/devices
