version: 1.1
debug: true
network:
  type: tcp
  address: ":5001"
  tls:
    skipVerify: true
    key: /tmp/ssl/emulator-plugin.key
    cert: /tmp/ssl/emulator-plugin.crt
    caCerts:
      - /tmp/ssl/rootCA.crt
