version: 2
jobs:
  build:
    working_directory: /synse-server
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - synse-server-{{ .Branch }}
          paths:
            - /caches/synse-server.tar
      - run:
          name: Load image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/synse-server.tar | true
      - run:
          name: Docker Build
          command: |
            version=$(cat synse/__init__.py | grep "__version__ =" | awk '{print $3}' | sed "s/'//g")
            docker build --cache-from=synse-server -f dockerfile/release.dockerfile \
              -t vaporio/synse-server-internal:latest \
              -t vaporio/synse-server-internal:$version .
      - run:
          name: Save image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/synse-server.tar vaporio/synse-server-internal
      - save_cache:
          key: synse-server-{{ .Branch }}
          paths:
            - /caches/synse-server.tar
      - deploy:
          name: Push to DockerHub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PS
              for img in $(docker images --format "{{.Repository}}:{{.Tag}}" vaporio/synse-server-internal); do
                docker push $img
              done
            fi
