version: 2
jobs:
  build:
    docker:
      - image: python
    working_directory: /synse-server
    environment:
      - DOCKER_VERSION=17.09.1-ce
      - COMPOSE_VERSION=1.18.0
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker Client
          command: |
            set -x
            curl -L -o /tmp/docker-${DOCKER_VERSION}.tgz https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
            tar -xz -C /tmp -f /tmp/docker-${DOCKER_VERSION}.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Docker Compose Build
          command: docker-compose -f compose/release.yml build
      - run:
          name: Run tests
          command: |
            make test
