# Configuration for the emulator plugin built-in to Synse Server
version: 1.0
name: emulator
debug: true
network:
  type: unix
  address: emulator.sock
settings:
  mode: parallel
  read:
    interval: 1s
  write:
    interval: 1s