version: 1.0
prototypes:
  - type: temperature
    model: emul8-temp
    manufacturer: Vapor IO
    protocol: emulator
    output:
      - type: temperature
        data_type: float
        unit:
          name: degrees celsius
          symbol: C
        precision: 2
        range:
          min: 0
          max: 100