# Google Cloud Builder definition for synse-server images.
steps:
- id: synse-server
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/synse-server:$COMMIT_SHA', '-f', 'dockerfile/release.dockerfile', '.']
  waitFor:
  - "-"
- id: synse-server-tag
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/synse-server:$TAG_NAME', '-f', 'dockerfile/release.dockerfile', '.']
  waitFor:
  - "-"
images:
- 'gcr.io/$PROJECT_ID/synse-server:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/synse-server:$TAG_NAME'
