version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: airflow
    metadata:
      model: emul8-air
    outputs:
      - type: airflow
    instances:
      - info: Synse Airflow Sensor
        location: r1vec
        data:
          id: 1
