version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: fan
    metadata:
      model: emul8-fan
    outputs:
      - type: fan.speed
    instances:
      - info: Synse Fan
        location: r1vec
        data:
          id: 1
