version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: humidity
    metadata:
      model: emul8-humidity
    outputs:
      - type: humidity
      - type: temperature
    instances:
      - info: Synse Humidity Sensor
        location: r1vec
        data:
          id: 1