version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: led
    metadata:
      model: emul8-led
    outputs:
      - type: led.state
      - type: led.color
    instances:
      - info: Synse LED
        location: r1vec
        data:
          id: 1
      - info: Synse backup LED
        location: r1vec
        data:
          id: 2
