version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: pressure
    metadata:
      model: emul8-pressure
    outputs:
      - type: pressure
    instances:
      - info: Synse Pressure Sensor 1
        location: r1vec
        data:
          id: 1
      - info: Synse Pressure Sensor 2
        location: r1vec
        data:
          id: 2