version: 1.0
locations:
  - name: r1vec
    rack:
      name: rack-1
    board:
      name: vec
devices:
  - name: temperature
    metadata:
      model: emul8-temp
    outputs:
      - type: temperature
    instances:
      - info: Synse Temperature Sensor 1
        location: r1vec
        data:
          id: 1
      - info: Synse Temperature Sensor 2
        location: r1vec
        data:
          id: 2
      - info: Synse Temperature Sensor 3
        location: r1vec
        data:
          id: 3
      - info: Synse Temperature Sensor 4
        location: r1vec
        data:
          id: 4
      - info: Synse Temperature Sensor 5
        location: r1vec
        data:
          id: 5
