# ------------------------------------------------------------------------
#  \\//
#   \/aporIO - Vapor Common
#
#  Build Vapor Common docker images from the current directory.
#
#  Author: Erick Daniszewski (erick@vapor.io)
#  Date:   12 Jan 2016
# ------------------------------------------------------------------------

# Include common functionality for docker cleanup.
include ../make_docker_common

# build directive used by vapor-build repo to build services. this should
# not be removed.
build: ;
