#!/usr/bin/env python
""" Constant values used for SNMP.

    \\//
     \/apor IO
"""

# Emulator Test measurement units.
# We expect these in the SNMP results. They are defined in the MIB.
EMULATOR_TEST_UNIT_UNDEFINED = 1
EMULATOR_TEST_UNIT_TEMPERATURE = 2
EMULATOR_TEST_UNIT_CURRENT = 3
EMULATOR_TEST_UNIT_POWER = 4
EMULATOR_TEST_UNIT_EFFECTIVE_POWER = 5
EMULATOR_TEST_UNIT_HUMIDITY = 6
EMULATOR_TEST_UNIT_VOLTAGE = 7
EMULATOR_TEST_UNIT_ENERGY = 8
EMULATOR_TEST_UNIT_FREQUENCY = 9
EMULATOR_TEST_UNIT_ACCESS = 10
EMULATOR_TEST_UNIT_LEAKAGE = 11
EMULATOR_TEST_UNIT_PERCENT = 12
EMULATOR_TEST_UNIT_RPM = 13
EMULATOR_TEST_UNIT_CO2 = 14
EMULATOR_TEST_UNIT_PUE = 15  # Power usage effectiveness
EMULATOR_TEST_UNIT_FLOW = 16
EMULATOR_TEST_UNIT_TIME = 17
EMULATOR_TEST_UNIT_COSTS = 18
EMULATOR_TEST_UNIT_IMP = 19  # TODO: Find out what this is. Some Imperial Unit?
EMULATOR_TEST_UNIT_HEAT_CAPACITY = 20
EMULATOR_TEST_UNIT_CONSTANT = 21
EMULATOR_TEST_UNIT_TEMPERATURE_DIFF = 22
EMULATOR_TEST_UNIT_TIMESPAN = 23  # TODO: Will need formatting / examples here. This timespan may not be a broad standard.
EMULATOR_TEST_UNIT_CYCLES = 24

EMULATOR_TEST_UNIT_PULSE_RATE = 34
EMULATOR_TEST_UNIT_PRESSURE = 35
EMULATOR_TEST_UNIT_ACCELERATION = 36
EMULATOR_TEST_UNIT_TIMESPAN_TICKS = 37

# Need a map of the above to our device type strings.
EMULATOR_TEST_UNIT_TO_DEVICE_TYPE_MAP = {
    EMULATOR_TEST_UNIT_UNDEFINED: "undefined",
    EMULATOR_TEST_UNIT_TEMPERATURE: "temperature",
    EMULATOR_TEST_UNIT_CURRENT: "current",
    EMULATOR_TEST_UNIT_POWER: "power",
    EMULATOR_TEST_UNIT_EFFECTIVE_POWER: "effective_power",
    EMULATOR_TEST_UNIT_HUMIDITY: "humidity",
    EMULATOR_TEST_UNIT_VOLTAGE: "voltage",
    EMULATOR_TEST_UNIT_ENERGY: "energy",
    EMULATOR_TEST_UNIT_FREQUENCY: "frequency",
    EMULATOR_TEST_UNIT_ACCESS: "access",
    EMULATOR_TEST_UNIT_LEAKAGE: "leakage",
    EMULATOR_TEST_UNIT_PERCENT: "percent",
    # Hijacking this one for fan_speed. It may be that we have a one to many mapping in the future.
    EMULATOR_TEST_UNIT_RPM: "fan_speed",  # MIB has rpm.
    EMULATOR_TEST_UNIT_CO2: "co2",
    EMULATOR_TEST_UNIT_PUE: "pue",
    EMULATOR_TEST_UNIT_FLOW: "flow",
    EMULATOR_TEST_UNIT_TIME: "time",  # TODO: Be careful with data format. Need a real walk for this.
    EMULATOR_TEST_UNIT_COSTS: "costs",
    EMULATOR_TEST_UNIT_IMP: "imp",
    EMULATOR_TEST_UNIT_HEAT_CAPACITY: "heat_capacity",
    EMULATOR_TEST_UNIT_CONSTANT: "constant",
    EMULATOR_TEST_UNIT_TEMPERATURE_DIFF: "temperature_diff",
    EMULATOR_TEST_UNIT_CYCLES: "cycles",
    EMULATOR_TEST_UNIT_PULSE_RATE: "pulse_rate",
    EMULATOR_TEST_UNIT_PRESSURE: "pressure",
    EMULATOR_TEST_UNIT_ACCELERATION: "acceleration",
    EMULATOR_TEST_UNIT_TIMESPAN_TICKS: "timespan_ticks",
}
