version: "2"
services:
  graphql-test:
    container_name: synse-graphql-test
    image: vaporio/synse-graphql-test
    build:
      context: ..
      dockerfile: dockerfile/graphql-test.dockerfile
    volumes:
      - ../:/synse
    links:
      - synse-server

  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    # we need to start up an I2C emulator as well in order to get pressure
    # sensor data while testing.
    command: start-i2c-emulator i2c_emulator_config.json
    ports:
      - 5000:5000
    environment:
      - VAPOR_DEBUG=true
    volumes:
      - ../test/config/bmc.json:/synse/bmc_config.json
      - ../test/config/i2c.json:/synse/i2c_config.json
      - ../test/config/ipmi_i2c.json:/synse/override/config.json
      - ../test/emulator/i2c.json:/synse/i2c_emulator_config.json
    links:
      - ipmi-emulator:ipmi-emulator-1-1
      - ipmi-emulator:ipmi-emulator-1-2
      - ipmi-emulator:ipmi-emulator-1-3
      - ipmi-emulator:ipmi-emulator-1-4
      - ipmi-emulator:ipmi-emulator-1-5
      - ipmi-emulator:ipmi-emulator-1-6
      - ipmi-emulator:ipmi-emulator-2-1
      - ipmi-emulator:ipmi-emulator-2-2
      - ipmi-emulator:ipmi-emulator-2-3
      - ipmi-emulator:ipmi-emulator-2-4
      - ipmi-emulator:ipmi-emulator-2-5
      - ipmi-emulator:ipmi-emulator-2-6
      - ipmi-emulator:ipmi-emulator-3-1
      - ipmi-emulator:ipmi-emulator-3-2
      - ipmi-emulator:ipmi-emulator-3-3
      - ipmi-emulator:ipmi-emulator-3-4
      - ipmi-emulator:ipmi-emulator-3-5
      - ipmi-emulator:ipmi-emulator-3-6
      - ipmi-emulator:ipmi-emulator-4-1
      - ipmi-emulator:ipmi-emulator-4-2
      - ipmi-emulator:ipmi-emulator-4-3
      - ipmi-emulator:ipmi-emulator-4-4
      - ipmi-emulator:ipmi-emulator-4-5
      - ipmi-emulator:ipmi-emulator-4-6
      - ipmi-emulator:ipmi-emulator-5-1
      - ipmi-emulator:ipmi-emulator-5-2
      - ipmi-emulator:ipmi-emulator-5-3
      - ipmi-emulator:ipmi-emulator-5-4
      - ipmi-emulator:ipmi-emulator-5-5
      - ipmi-emulator:ipmi-emulator-5-6
      - ipmi-emulator:ipmi-emulator-6-1
      - ipmi-emulator:ipmi-emulator-6-2
      - ipmi-emulator:ipmi-emulator-6-3
      - ipmi-emulator:ipmi-emulator-6-4
      - ipmi-emulator:ipmi-emulator-6-5
      - ipmi-emulator:ipmi-emulator-6-6

  ipmi-emulator:
    container_name: synse-server-ipmi-emulator
    image: vaporio/ipmi-emulator-x64
    ports:
      - 623
