version: "3"
services:
  synse-test:
    container_name: synse-test
    image: vaporio/synse-server-test:${GIT_VER}
    build:
      context: ..
      dockerfile: dockerfile/test.dockerfile
    volumes:
      - ..:/code
    command: bin/run_tests.sh unit
