#
# compose.yml
#
# An example deployment of Synse Server and the Emulator Plugin
# configured to communicate over TCP.
#

version: '3'
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server:latest
    ports:
    - '5000:5000'
    environment:
      # Run the server in debug mode
      SYNSE_LOGGING: debug
      # Register a TCP plugin with hostname 'emulator', port 5001
      SYNSE_PLUGIN_TCP: emulator:5001
    links:
    - emulator

  emulator:
    container_name: emulator
    image: vaporio/emulator-plugin:latest
    expose:
    - '5001'
    command: ['--debug']
    volumes:
      # Mount the custom plugin config into the default plugin configuration
      # search path
      - ./plugin-config.yaml:/etc/synse/plugin/config/config.yaml

