FROM vaporio/vapor-endpoint-base-x64:1.0
MAINTAINER Erick Daniszewski <erick@vapor.io>

# Copy and install the package from WORKDIR.
# The tests point to the package installation path to run (full path).
WORKDIR /tests
COPY vapor_common-1.0.tar.gz /tests

# Install the vapor_common package.
RUN pip install -I vapor_common-1.0.tar.gz